services:
  users:
    container_name: quizgpt-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb+srv://admin:adminPass@quizgpt.itkoce0.mongodb.net/?retryWrites=true&w=majority&appName=QuizGPT

  api:
    container_name: quizgpt-api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyAqDFLl2zouiaukXx8FQ9bnZNDyW2oJw2U

  frontend:
    container_name: quizgpt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - users
      - api

