services:
  api:
    container_name: quizgpt-api
    image: aesbube/quizgpt-api:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    