services:
  users:
    container_name: quizgpt-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    image: aesbube/quizgpt-users:latest
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI

  api:
    container_name: quizgpt-api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: aesbube/quizgpt-api:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY

  frontend:
    container_name: quizgpt-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aesbube/quizgpt-frontend:latest
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - users
      - api

