services:
  mongo:
    container_name: quizgpt-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  users:
    container_name: quizgpt-users
    build:
      context: ./backend/users
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/quizgpt_db  

  api:
    container_name: quizgpt-api
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"


volumes:
  mongo_data: